# Generated by Django 4.2 on 2025-09-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
