# Generated by Django 4.2 on 2025-09-15 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_property_bathrooms_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default='00000-0000', max_length=10, validators=[django.core.validators.RegexValidator(message='Zip code must be in the format 12345-6789', regex='^\\d{5}-\\d{4}$')]),
        ),
    ]
